# roles/user-config/tasks/main.yml

- name: change password
  ansible.builtin.user:
    name: "{{ vm_usr }}"
    update_password: always
    password: "{{ vm_pwd_test }} | password_hash('sha512')"
    state: present
