# roles/pwd-change/tasks/main.yml

- name: change password use command
  ansible.builtin.expect:
    command: "passwd {{ vm_usr }}"
    responses:
      Current password: "{{ vm_pwd }}"
      New password: "{{ vm_pwd_test }}"
      Retype new password: "{{ vm_pwd_test }}"
